#!/usr/bin/env python
# -*- coding: utf-8 -*-
import argparse, sys
from igraph import *
from readfile import ReadFile
import datetime
import time

#def main():
#    pass
  
def ordenarLanguages():
    list_ordenado = list(reversed(sorted(data.ted_talks['languages'])))
    for i in range(0,len(data.ted_talks['languages'])):
        for j in range(0,10):
            if int(list_ordenado[j]) == int(data.ted_talks['languages'][i]):
                print  j+1 , "º mais traduzido: " , data.ted_talks['name'][i], " e foi traduzido para: " , data.ted_talks['languages'][i], " línguas."

def ordenarVisualizacoes():
    list_ordenado = list(reversed(sorted(data.ted_talks['views'])))
    for i in range(0,len(data.ted_talks['views'])):
        for j in range(0,10):
            if int(list_ordenado[j]) == int(data.ted_talks['views'][i]):
            #if data.ted_talks['comments'][i] == 6404:
                print  j+1 , "º mais visto: " , data.ted_talks['name'][i], " e ", data.ted_talks['views'][i], " visualizações"

def ordenarComentarios():
    list_ordenado = list(reversed(sorted(data.ted_talks['comments'])))
    for i in range(0,len(data.ted_talks['comments'])):
        for j in range(0,10):
            if int(list_ordenado[j]) == int(data.ted_talks['comments'][i]):
            #if data.ted_talks['comments'][i] == 6404:
                print  j+1 , "º mais comentado: " , data.ted_talks['name'][i], "Ocupação: " , data.ted_talks['speaker_occupation'][i] , " e ", data.ted_talks['comments'][i], " comentarios e a descrição é: " , data.ted_talks['description'][i]

    
def IdentificarInfos():
    for i in range(0,len(data.ted_talks['name'])):
       if data.ted_talks['name'][i] == "Try something new for 30 days" :
           print data.ted_talks['languages'][i]
           print data.ted_talks['views'][i]
           print data.ted_talks['tags'][i]
           
def Tempo():
    #data = ReadFile(filename)
    for i in range(0,len(data.ted_talks['published_date'])):
        print time.ctime(int(data.ted_talks['published_date'][i]))           

if __name__ == "__main__":
    global data
    parser = argparse.ArgumentParser()
    parser.add_argument("-f", type=str, default='../database/ted_talks.csv',
                        help="Nome do arquivo.")
    args = parser.parse_args()
    filename = args.f
    data = ReadFile(filename)

    #main()
    #Tempo()
    #ordenarLanguages()
    #IdentificarInfos()
    #ordenarVizualizacoes()
    #ordenarComentarios()
    #ordenarVisualizacoes()
    
    